### Makefile for the "mastermaster" WAM example program

BIN = mastermaster
OBJ = mastermaster.o refgen_mastermaster.o
CC = gcc

CFLAGS += -std=c89 -pedantic-errors -Wall -Werror -Wno-long-long
LDFLAGS += -lbarrett -lcurses

${BIN} : ${OBJ}

.PHONY : clean
clean:
	rm -f ${OBJ} ${BIN}
