/* auto-generated by gensrv_java from /home/robot/libbarrett/ros/wam_ros/srv/WamCommands.srv.  Do not edit! */
package ros.pkg.wam_ros.srv;

import java.nio.ByteBuffer;

public class WamCommands extends ros.communication.Service<WamCommands.Request, WamCommands.Response> 
{

public static String __s_getDataType() { return "wam_ros/WamCommands"; }
public static String __s_getMD5Sum() { return "5487903b3c35697e058b56c00a8836fa"; }

public String getDataType() { return WamCommands.__s_getDataType(); }
public String getMD5Sum() { return WamCommands.__s_getMD5Sum(); }

public static class Request extends ros.communication.Message
{

  public long command;
  public double[] desiredJoints;

  public Request() {
 super();
  desiredJoints = new double[7];

  }
  public static java.lang.String __s_getDataType() { return "wam_ros/WamCommandsRequest"; }
  public static java.lang.String __s_getMD5Sum() { return ""; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "uint64 command\n" + 
    "float64[7] desiredJoints\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public static java.lang.String __s_getServerMD5Sum() { return ("5487903b3c35697e058b56c00a8836fa"); }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String  __s_getServiceDataType() { return ("wam_ros/WamCommands"); }
  public java.lang.String getServiceDataType() { return __s_getServiceDataType(); }
  public Request clone() {
    Request clone = (Request)super.clone();
      desiredJoints =  (double[])(clone.desiredJoints.clone());
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      m.put("command", "long");
     m.put("desiredJoints", "double[]");
     return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Request)) throw new RuntimeException("Invalid Type");
    Request __m2 = (Request) __m;
    command = __m2.command;
    desiredJoints = __m2.desiredJoints;
    }

  public int serializationLength() 
  {
    int __l = 0;
    __l += 8; // command
    __l += 0; // desiredJoints
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
    bb.putLong(command);
    bb.asDoubleBuffer().put(desiredJoints);  }
  public void deserialize(ByteBuffer bb)  {
    command = bb.getLong();
     int desiredJoints_len = 7;
    desiredJoints = new double[desiredJoints_len];
    bb.asDoubleBuffer().get(desiredJoints);  }
}

public static class Response extends ros.communication.Message
{

  public java.lang.String response;

  public Response() {
 super();
    response = new java.lang.String();

  }
  public static java.lang.String __s_getDataType() { return "wam_ros/WamCommandsResponse"; }
  public static java.lang.String __s_getMD5Sum() { return ""; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "string response\n" + 
    "\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public static java.lang.String __s_getServerMD5Sum() { return ("5487903b3c35697e058b56c00a8836fa"); }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String  __s_getServiceDataType() { return ("wam_ros/WamCommands"); }
  public java.lang.String getServiceDataType() { return __s_getServiceDataType(); }
  public Response clone() {
    Response clone = (Response)super.clone();
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      m.put("response", "java.lang.String");
     return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Response)) throw new RuntimeException("Invalid Type");
    Response __m2 = (Response) __m;
    response = __m2.response;
    }

  public int serializationLength() 
  {
    int __l = 0;
    __l += 4 + response.length(); // response
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
    Serialization.writeString(bb, response);
  }
  public void deserialize(ByteBuffer bb)  {
    response = Serialization.readString(bb);
  }
}

public WamCommands.Request createRequest() { return new WamCommands.Request(); }public WamCommands.Response createResponse() { return new WamCommands.Response(); }}

