%: ./src/%.o $(USER_OBJS)
	@echo 'Building target: $@'
	@echo 'Invoking: GCC C++ Linker'
	g++ -L/home/robot/libbarrett/library/Debug -L/home/robot/libbarrett/cdlbt/Debug -Xlinker -rpath /home/robot/libbarrett/library/Debug -Xlinker -rpath /usr/xenomai/lib -o"$@" ./src/$@.o $(USER_OBJS) $(LIBS)
	@echo 'Finished building target: $@'
	@echo ' '

	
#all: can_terminal cartesian_hold hand_feedback HAPI_haptics haptics high_level_wam log_ft_data log_velocity low_level_wam master_master move_to network_haptics teach update_properties zero_torque
all: log_ft_data
