%: ./src/%.o $(USER_OBJS)
	@echo 'Building target: $@'
	@echo 'Invoking: GCC C++ Linker'
	g++ -L/home/robot/libbarrett/library/Debug -Xlinker -rpath /usr/xenomai/lib -o"$@" ./src/$@.o $(USER_OBJS) $(LIBS) -lcurses
	@echo 'Finished building target: $@'
	@echo ' '

	
#all: can_terminal cartesian_hold friction_data hand_feedback haptics high_level_wam load_ft_cal log_ft_data log_ft_data_with_wam log_sg_data log_velocity low_level_wam master_master move_to network_haptics puck_terminal read_safety_state tactile_test teach update_properties zero_torque
all: can_terminal
