/* auto-generated by genmsg_cpp from /home/robot/libbarrett/ros/wam_ros/msg/Joints.msg.  Do not edit! */
#ifndef WAM_ROS_JOINTS_H
#define WAM_ROS_JOINTS_H

#include <string>
#include <vector>
#include "ros/message.h"
#include "ros/time.h"

namespace wam_ros
{

//! \htmlinclude Joints.msg.html

class Joints : public ros::Message
{
public:
  typedef boost::shared_ptr<Joints> Ptr;
  typedef boost::shared_ptr<Joints const> ConstPtr;

  typedef std::string _j_type;

  std::string j;

  Joints() : ros::Message()
  {
  }
  Joints(const Joints &copy) : ros::Message(),
    j(copy.j)
  {
    (void)copy;
  }
  Joints &operator =(const Joints &copy)
  {
    if (this == &copy)
      return *this;
    j = copy.j;
    return *this;
  }
  virtual ~Joints() 
  {
  }
  inline static std::string __s_getDataType() { return std::string("wam_ros/Joints"); }
  inline static std::string __s_getMD5Sum() { return std::string("0faeaaa42c2070611310a54ecba6c3ef"); }
  inline static std::string __s_getMessageDefinition()
  {
    return std::string(
    "string j\n"
    "\n"
    "\n"
    );
  }
  inline virtual const std::string __getDataType() const { return __s_getDataType(); }
  inline virtual const std::string __getMD5Sum() const { return __s_getMD5Sum(); }
  inline virtual const std::string __getMessageDefinition() const { return __s_getMessageDefinition(); }
  inline uint32_t serializationLength() const
  {
    unsigned __l = 0;
    __l += 4 + j.length(); // j
    return __l;
  }
  virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    unsigned __ros_j_len = j.length();
    SROS_SERIALIZE_PRIMITIVE(write_ptr, __ros_j_len);
    SROS_SERIALIZE_BUFFER(write_ptr, j.c_str(), __ros_j_len);
    return write_ptr;
  }
  virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    unsigned __ros_j_len;
    SROS_DESERIALIZE_PRIMITIVE(read_ptr, __ros_j_len);
    j = std::string((const char *)read_ptr, __ros_j_len);
    read_ptr += __ros_j_len;
    return read_ptr;
  }
};

typedef boost::shared_ptr<Joints> JointsPtr;
typedef boost::shared_ptr<Joints const> JointsConstPtr;


}

#endif
