#!/usr/bin/python

"""
	Copyright 2012 Barrett Technology <support@barrett.com>

	This file is part of libbarrett.

	This version of libbarrett is free software: you can redistribute it
	and/or modify it under the terms of the GNU General Public License as
	published by the Free Software Foundation, either version 3 of the
	License, or (at your option) any later version.

	This version of libbarrett is distributed in the hope that it will be
	useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
	GNU General Public License for more details.

	You should have received a copy of the GNU General Public License along
	with this version of libbarrett.  If not, see
	<http://www.gnu.org/licenses/>.

	Further, non-binding information about licensing is available at:
	<http://wiki.barrett.com/libbarrett/wiki/LicenseNotes>
"""

"""
This utility installs libbarrett configuration files into the specified directory.
If there are already
configuration files in the directory, they will be backed-up and updated as
necessary according to the CONFIG_VERSION setting.
"""

import sys, os
from datetime import date
import re, shutil, errno
import argparse


DEFAULT_SOURCE_DIR = "../config/"
DEFAULT_DEST_DIR = "/etc/barrett/"

VERS_PATTERN = "^CONFIG_VERSION\s*=\s*(\d+);$"

MAIN_VERS_FILE = "default.conf"
MAIN_CONFIG_FILES = [MAIN_VERS_FILE, "wam4.conf", "wam7g.conf", "wam7w.conf", "calibration_data"]

CAL_VERS_FILE = "calibration.conf"
CAL_CONFIG_FILES = [CAL_VERS_FILE]


def main():
	args = parseArguments()
	print ">>> Source: %s" % args.source
	print ">>> Destination: %s" % args.dest
	
	backupDir = getBackupDirName(args.dest)
	installConfig(args.source, args.dest, backupDir, MAIN_VERS_FILE, MAIN_CONFIG_FILES)


def parseArguments():
	ap = argparse.ArgumentParser(description="Install or upgrade libbarrett configuration files.")
	ap.add_argument("-s", "--source", default=DEFAULT_SOURCE_DIR, help="the source directory (default: %(default)s)")
	ap.add_argument("-d", "--dest", default=DEFAULT_DEST_DIR, help="the destination directory (default: %(default)s)")

	args = ap.parse_args()
	args.dest = cleanDirPath(args.dest)
	args.source = cleanDirPath(args.source)
	return args

def cleanDirPath(p):
	p = os.path.abspath(os.path.expanduser(p))
	if not os.path.isdir(p):
		print "ERROR: %s is not a directory." % p
		sys.exit(1)
	return p


def getBackupDirName(d):
	base = date.today().strftime("BACKUP-%Y%m%d-")
	i = 0
	while True:
		p = joinPaths(d, base + str(i))
		if not os.path.exists(p):
			break
		i += 1
	return p

def joinPaths(a, b):
	return os.path.abspath(a + "/" + b)


def installConfig(s, d, backupDir, versFile, configFiles):
	print ">>> Updating configuration group: %s" % versFile
	
	sVers = getConfigVers(s, versFile)
	if sVers == -1:
		print "ERROR: \"%s\" not present in source directory." % versFile
		return
	dVers = getConfigVers(d, versFile)
	print "  --> Source version:", sVers
	print "  --> Destination version:", dVers
	
	if sVers == dVers:
		print "  --> Group is already up to date" % versFile
		return
	else:
		print "  --> Creating backup in:", backupDir
		copyGroup(d, backupDir, configFiles, False)
		print "  --> Updating"

def getConfigVers(d, f):
	""" Special values: -1 means file not present, 0 means CONFIG_VERSION not present"""
	
	p = joinPaths(d, f)
	if not os.path.exists(p):
		return -1
	if not os.path.isfile(p):
		print "ERROR: %s is not a file." % p
		sys.exit(1)
	
	vers = 0
	fh = open(p, 'r')
	for line in fh:
		m = re.match(VERS_PATTERN, line)
		if m:
			if vers != 0:
				# Then there were two matches
				print "ERROR: %s has multiple CONFIG_VERSION settings." % p
				sys.exit(1)
			vers = int(m.group(1))
	return vers

def copyGroup(s, d, fileList, strict):
	os.mkdir(d)
	for f in fileList:
		if not copyFileOrDir(joinPaths(s, f), joinPaths(d, f)) and strict:
			if strict or e.errno != errno.ENOENT:
				print "ERROR: %s does not exist." % joinPaths(s, f)
				sys.exit(2)

def copyFileOrDir(src, dst):
	assert not os.path.exists(dst)
	if not os.path.exists(src):
		return False
	
	if os.path.isdir(src):
		shutil.copytree(src, dst)
	else:
		shutil.copy2(src, dst)
	return True


if __name__ == "__main__":
	main()

