#!/bin/bash

# Sets the active WAM.

ip=$1
scriptpath=`dirname $0`

if [ -z "$ip" ]
then
   echo "You must provide the hostname (and optionally username) of the WAM you wish to develop on: [user@hostname]"
   exit
fi


# save the IP address for the other build scripts to find
echo "Saving the hostname..."
echo $ip > $scriptpath/wam-hostname.txt

# allow us to login to the WAM without typing the password every time
$scriptpath/sshsetup $ip

#echo "Syncing clocks..."
#$scriptpath/wamdo date `date +%m%d%H%M%Y.%S -u`

echo "Done!"

