%: ./src/%.o $(USER_OBJS)
	@echo 'Building target: $@'
	@echo 'Invoking: GCC C++ Linker'
	g++ -L/root/libbarrett/library/Debug -L/root/libbarrett/cdlbt/Debug -Xlinker -rpath /root/libbarrett/library/Debug -Xlinker -rpath /usr/xenomai/lib -o"$@" ./src/$@.o $(USER_OBJS) $(LIBS)
	@echo 'Finished building target: $@'
	@echo ' '

	
#all: cartesian_hold high_level_wam low_level_wam master_master network_haptics teach zero_torque
all: teach
