%: ./src/%.o $(USER_OBJS)
	@echo 'Building target: $@'
	@echo 'Invoking: GCC C++ Linker'
	g++ -L/home/robot/libbarrett/library/Debug -L/home/robot/libbarrett/cdlbt/Debug -Xlinker -rpath /home/robot/libbarrett/library/Debug -Xlinker -rpath /usr/xenomai/lib -o"$@" ./src/$@.o $(USER_OBJS) $(LIBS)
	@echo 'Finished building target: $@'
	@echo ' '

	
#all: cartesian_hold hand_feedback high_level_wam low_level_wam master_master teach tutorial update_properties zero_torque
all: tutorial hand_feedback update_properties
