#!/bin/bash

# Sets the active WAM.

ip=$1
scriptpath=`dirname $0`

if [ -z "$ip" ]
then
   echo "You must provide the IP address of the WAM you wish to develop on."
   exit
fi


# save the IP address for the other build scripts to find
echo "Saving the IP address ..."
echo $ip > $scriptpath/wam-ip.txt

# allow us to login to the WAM without typing the password every time
$scriptpath/sshsetup $ip

echo "Done!"

