#!/bin/bash

if [ $# -eq 0 ]
then
	echo "Synchronizes files to the active WAM, and then builds the specified project. Does not copy hidden or temporary files."
	echo "	Usage: wam-make {build-dir} {make arguments}"
	echo "	As an Eclipse make command: \${workspace_loc:}/common/wam-make \${ProjName}/\${ConfigName}"
	echo "	Must be executed from the project's build directory, which must be an immediate child of the project directory."
	exit
fi


scriptpath=`dirname $0`

builddir=$1
shift

# copy the files over to the WAM
rsync -av --delete --exclude=".*" --exclude="*~" \
	$scriptpath/.. \
	root@`cat $scriptpath/wam-ip.txt`:libbarrett/trunk \
&& \
$scriptpath/wamdo "cd libbarrett/trunk/$builddir; make" $*

