/* auto-generated by gensrv_cpp from /home/robot/libbarrett/ros/wam_ros/srv/WamCommands.srv.  Do not edit! */
#ifndef SRV_WAM_ROS_WAMCOMMANDS_H
#define SRV_WAM_ROS_WAMCOMMANDS_H

#include <string>
#include <cstring>
#include <vector>
#include <map>

namespace wam_ros
{

struct WamCommands
{

inline static std::string getDataType() { return "wam_ros/WamCommands"; }
inline static std::string getMD5Sum() { return "a4d35f165bc8241b74b54e4eef915a13"; }

//! \htmlinclude Request.msg.html

class Request : public ros::Message
{
public:
  typedef boost::shared_ptr<Request> Ptr;
  typedef boost::shared_ptr<Request const> ConstPtr;

  typedef uint64_t _command_type;

  uint64_t command;

  Request() : ros::Message(),
    command(0)
  {
  }
  Request(const Request &copy) : ros::Message(),
    command(copy.command)
  {
    (void)copy;
  }
  Request &operator =(const Request &copy)
  {
    if (this == &copy)
      return *this;
    command = copy.command;
    return *this;
  }
  virtual ~Request() 
  {
  }
  inline static std::string __s_getDataType() { return std::string("wam_ros/WamCommandsRequest"); }
  inline static std::string __s_getMD5Sum() { return std::string(""); }
  inline static std::string __s_getMessageDefinition()
  {
    return std::string(
    "uint64 command\n"
    "\n"
    );
  }
  inline virtual const std::string __getDataType() const { return __s_getDataType(); }
  inline virtual const std::string __getMD5Sum() const { return __s_getMD5Sum(); }
  inline virtual const std::string __getMessageDefinition() const { return __s_getMessageDefinition(); }
  inline static std::string __s_getServerMD5Sum() { return std::string("a4d35f165bc8241b74b54e4eef915a13"); }
  inline virtual const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum(); }
  inline static std::string __s_getServiceDataType() { return std::string("wam_ros/WamCommands"); }
  inline virtual const std::string __getServiceDataType() const { return __s_getServiceDataType(); }
  inline uint32_t serializationLength() const
  {
    unsigned __l = 0;
    __l += 8; // command
    return __l;
  }
  virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    SROS_SERIALIZE_PRIMITIVE(write_ptr, command);
    return write_ptr;
  }
  virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    SROS_DESERIALIZE_PRIMITIVE(read_ptr, command);
    return read_ptr;
  }
};

typedef boost::shared_ptr<Request> RequestPtr;
typedef boost::shared_ptr<Request const> RequestConstPtr;

//! \htmlinclude Response.msg.html

class Response : public ros::Message
{
public:
  typedef boost::shared_ptr<Response> Ptr;
  typedef boost::shared_ptr<Response const> ConstPtr;

  typedef std::string _response_type;

  std::string response;

  Response() : ros::Message()
  {
  }
  Response(const Response &copy) : ros::Message(),
    response(copy.response)
  {
    (void)copy;
  }
  Response &operator =(const Response &copy)
  {
    if (this == &copy)
      return *this;
    response = copy.response;
    return *this;
  }
  virtual ~Response() 
  {
  }
  inline static std::string __s_getDataType() { return std::string("wam_ros/WamCommandsResponse"); }
  inline static std::string __s_getMD5Sum() { return std::string(""); }
  inline static std::string __s_getMessageDefinition()
  {
    return std::string(
    "string response\n"
    "\n"
    "\n"
    );
  }
  inline virtual const std::string __getDataType() const { return __s_getDataType(); }
  inline virtual const std::string __getMD5Sum() const { return __s_getMD5Sum(); }
  inline virtual const std::string __getMessageDefinition() const { return __s_getMessageDefinition(); }
  inline static std::string __s_getServerMD5Sum() { return std::string("a4d35f165bc8241b74b54e4eef915a13"); }
  inline virtual const std::string __getServerMD5Sum() const { return __s_getServerMD5Sum(); }
  inline static std::string __s_getServiceDataType() { return std::string("wam_ros/WamCommands"); }
  inline virtual const std::string __getServiceDataType() const { return __s_getServiceDataType(); }
  inline uint32_t serializationLength() const
  {
    unsigned __l = 0;
    __l += 4 + response.length(); // response
    return __l;
  }
  virtual uint8_t *serialize(uint8_t *write_ptr, uint32_t seq) const
  {
    unsigned __ros_response_len = response.length();
    SROS_SERIALIZE_PRIMITIVE(write_ptr, __ros_response_len);
    SROS_SERIALIZE_BUFFER(write_ptr, response.c_str(), __ros_response_len);
    return write_ptr;
  }
  virtual uint8_t *deserialize(uint8_t *read_ptr)
  {
    unsigned __ros_response_len;
    SROS_DESERIALIZE_PRIMITIVE(read_ptr, __ros_response_len);
    response = std::string((const char *)read_ptr, __ros_response_len);
    read_ptr += __ros_response_len;
    return read_ptr;
  }
};

typedef boost::shared_ptr<Response> ResponsePtr;
typedef boost::shared_ptr<Response const> ResponseConstPtr;

Request request;
Response response;

};

}

#endif
