#!/bin/bash

# Exit if any command fails
set -e

working_dir=__tgz_package_tmp
name=libbarrett-$1
package_dir=$working_dir/$name


echo ">>> Creating working directory"
mkdir $working_dir

echo ">>> Exporting project to working directory"
svn export . $package_dir

echo ">>> Removing the programming manual"
rm $package_dir/doc/libbarrett_programming_manual.doc

echo ">>> Removing the packaging script"
rm $package_dir/programs/build_tgz_package

echo ">>> Removing the property list generator"
rm $package_dir/src/products/property_list.py


echo ">>> Building tar-ball"
cd $working_dir
tar czf ../$name.tar.gz $name
cd ..


echo ">>> Removing working directory"
rm -R $working_dir
